# Generated by Django 5.1.7 on 2025-12-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='altura',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='peso_atual',
            field=models.FloatField(null=True),
        ),
    ]
